"""create user table

Revision ID: c36e90a7be0c
Revises: 
Create Date: 2024-06-20 17:04:16.903186

"""
from typing import Sequence, Union
import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36e90a7be0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('email', sa.String(), index=True, nullable=True),
        sa.Column('full_name', sa.String(), index=True, nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('google_id', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True, default=datetime.datetime.now()),
        sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.datetime.now()),
        sa.Column('email_verified', sa.Boolean(), nullable=True),
        sa.Column('role', sa.Integer(), nullable=True),
        sa.Column('avatar_url', sa.String(), nullable=True),
        sa.Column('forgot_password_token', sa.String(), nullable=True),
        sa.Column('activated', sa.Boolean(), nullable=True),
    )
    op.create_table(
        'email_verify',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('email', sa.String(), index=True, nullable=True),
        sa.Column('verify_code', sa.String(), index=True, nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.datetime.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_verify')
    op.drop_table('users')
    # ### end Alembic commands ###
