"""user table migration

Revision ID: 8d46c732457a
Revises: 819dc84761cc
Create Date: 2024-06-05 17:17:16.616687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import datetime

# revision identifiers, used by Alembic.
revision: str = '8d46c732457a'
down_revision: Union[str, None] = '819dc84761cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('email', sa.String(), index=True, nullable=True),
        sa.Column('full_name', sa.String(), index=True, nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('google_id', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True, default=datetime.datetime.now()),
        sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.datetime.now()),
        sa.Column('email_verified', sa.Boolean(), nullable=True),
        sa.Column('role', sa.Integer(), nullable=True),
        sa.Column('avatar_url', sa.String(), nullable=True),
        sa.Column('forgot_password_token', sa.String(), nullable=True),
        sa.Column('activated', sa.Boolean(), nullable=True),
    )
    op.create_table(
        'email_verify',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('email', sa.String(), index=True, nullable=True),
        sa.Column('verify_code', sa.String(), index=True, nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.datetime.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
